# Generated by Django 5.0.6 on 2024-05-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='NUMERO_DE_DOCUMENTO',
            new_name='NUMERO_DE_DOCUMENTO_INSTRUCTOR',
        ),
        migrations.AddField(
            model_name='instructor',
            name='PICTURE',
            field=models.ImageField(default='img/instructores/default.png', upload_to='img/instructores'),
        ),
    ]
